# Final Project - Movie Recommender
# DSC478 
# Eric Vistnes, Xiaojing Shen, Robert Kaszubski

Our goal is to explore ways in which we can recommend movies to users.
We have used different methods including Clustering, Classification, and SVD to do so.

Our dataset consisted of 17770 different movies rated by 480,189 with a grand total of 8,532,958,530 ratings. This proved difficult to process due to numerous issues with memory usage. We took several steps to make this dataset more manageable.

Please refer to the other attached Jupyter Notebooks for a breakdown on how we:

Combined the four txt files the dataset came in: Combine_Files.ipynb

Initially preprocessed and pivoted the entire dataset: CollaborativeFiltering.ipynd

Finally preprocesses and transformed the dataset to our final reduced version: Preprocessing and transformation.ipynd

### Begin Application:

We ask our user to rate movies they have seen from the most frequently rated in our dataset with the assumption that they have seen at least 5 of them.

In [3]:
import numpy as np
import pandas as pd

Read in our reduced and cleaned pickle file containing our dataset:

In [4]:
object = pd.read_pickle('cleanedMovie.pkl')
movies = pd.DataFrame(object)

Dataframe containing the most frequently rated films in order:

In [5]:
popular_movies = pd.DataFrame(movies["MovieID"].value_counts())

terms contains all of our movie titles, we remove unnecessary columns such as the release year:

In [6]:
terms = pd.read_csv('movie_titles.txt', sep='\t', encoding = "ISO-8859-1", header=None, index_col=0)
terms = terms.iloc[:,:2]
terms = terms.iloc[:,1:]

FileNotFoundError: [Errno 2] No such file or directory: 'movie_titles.txt'

Function to query movie title data and return the title for the given movieID:

In [5]:
def toTitle(MovieID):
    return terms.loc[ MovieID , : ][2]

Function to ask users to rate n number of movies to get ratings to use for recommendations:

Returns an array of the movies the user chose to rate in the format [[MovieID, rating]]

In [6]:
def initial_rating(n):
    print("These are the top",n, "most watched movies on our system:")
    print("Please rate at least 5 movies on a scale of 1 to 5 (1,2,3,4,5), you haven't seen it just hit Enter.")
    print("We can then start providing you recommendations based on your initial input!")
    print("")
    ratings = []
    for mov in range(0,n):
        ID = popular_movies.index[mov]
        title = toTitle(ID)
        print("You are rating", title)
        try:
            while True:
                b = int(input("Rate from 1 to 5: "))
                if b < 1 or b > 5:
                    print("Sorry, your response must be on a scale of 1 to 5.")
                    continue
                else:
                    break
            print("You rated", title, "as a", b)
            ratings.append([ID,b])
        except:
            print("You skipped", title)
            print("")
            continue
        print("")
        
        
    return ratings

#### Please follow the instructions below and try to rate at least 5 movies

In [7]:
user_ratings = initial_rating(20)

These are the top 20 most watched movies on our system:
Please rate at least 5 movies on a scale of 1 to 5 (1,2,3,4,5), you haven't seen it just hit Enter.
We can then start providing you recommendations based on your initial input!

You are rating Forrest Gump
Rate from 1 to 5: 4
You rated Forrest Gump as a 4

You are rating The Sixth Sense
Rate from 1 to 5:
You skipped The Sixth Sense

You are rating Pirates of the Caribbean: The Curse of the Black Pearl
Rate from 1 to 5: 4
You rated Pirates of the Caribbean: The Curse of the Black Pearl as a 4

You are rating The Matrix
Rate from 1 to 5:
You skipped The Matrix

You are rating Spider-Man
Rate from 1 to 5: 5
You rated Spider-Man as a 5

You are rating Men in Black
Rate from 1 to 5:
You skipped Men in Black

You are rating The Silence of the Lambs
Rate from 1 to 5: 5
You rated The Silence of the Lambs as a 5

You are rating Independence Day
Rate from 1 to 5:
You skipped Independence Day

You are rating Jurassic Park
Rate from 1 to 5: 4
You rated Jurassic Park as a 4

You are rating Gladiator
Rate from 1 to 5:
You skipped Gladiator

You are rating Ferris Bueller's Day Off
Rate from 1 to 5: 4
You rated Ferris Bueller's Day Off as a 4

You are rating Ocean's Eleven
Rate from 1 to 5: 4
You rated Ocean's Eleven as a 4

You are rating Raiders of the Lost Ark
Rate from 1 to 5: 5
You rated Raiders of the Lost Ark as a 5

You are rating Lord of the Rings: The Fellowship of the Ring
Rate from 1 to 5: 4
You rated Lord of the Rings: The Fellowship of the Ring as a 4

You are rating Minority Report
Rate from 1 to 5:
You skipped Minority Report

You are rating Speed
Rate from 1 to 5:
You skipped Speed

You are rating Meet the Parents
Rate from 1 to 5:
You skipped Meet the Parents

You are rating The Fugitive
Rate from 1 to 5:
You skipped The Fugitive

You are rating Braveheart
Rate from 1 to 5:
You skipped Braveheart

You are rating Pulp Fiction
Rate from 1 to 5: 4
You rated Pulp Fiction as a 4

Here is the data we just captured from your responses
Returned array of ratings in the format of: [MovieID, Rating] :

In [8]:
user_ratings

[[11283, 4],
 [1905, 4],
 [14410, 5],
 [2862, 5],
 [14312, 4],
 [6971, 4],
 [15107, 4],
 [10042, 5],
 [2452, 4],
 [11064, 4]]

### Now we are going to CLUSTER you based on your ratings

In [9]:
object = pd.read_pickle('cleanedMovie.pkl')
movies = pd.DataFrame(object)

Pivoting data to create a Customer by Movie Matrix of ratings to use for doc term clustering:

In [10]:
movieMatrix = movies.pivot_table(values='Rating', index='CustomerID', columns='MovieID')

Replacing missing values with 0's

In [11]:
movieMatrix = movieMatrix.fillna(0)
movie_arr = np.array(movieMatrix)

In [12]:
import kMeans
from sklearn.cluster import KMeans

Determining best k value:
Uncomment to run (takes a while) - look into Clustering.ipynb for output

In [13]:
#import matplotlib.pyplot as plt
#sse = {}
#for k in range(1, 20):
    #kmeans = KMeans(n_clusters=k).fit(movie_arr)
    #sse[k] = kmeans.inertia_

#plt.figure()
#plt.plot(list(sse.keys()), list(sse.values()))
#plt.xlabel("Number of cluster")
#plt.ylabel("SSE")
#plt.show()

#sse = {}
#for k in range(1, 10):
    #kmeans = KMeans(n_clusters=k).fit(movie_arr)
    #sse[k] = kmeans.inertia_
#plt.figure()
#plt.plot(list(sse.keys()), list(sse.values()))
#plt.xlabel("Number of cluster")
#plt.ylabel("SSE")
#plt.show()

In [14]:
kmeans = KMeans(n_clusters=10)
kmeans.fit(movie_arr)

KMeans(n_clusters=10)

In [15]:
def top_movies(df, n):
    for mov in range(0,n):
        print(toTitle(df.index[mov]),df.loc[df.index[mov]][0] )

In [16]:
np.set_printoptions(precision=2,suppress=True)

In [17]:
def print_clusters(kmeans, k, n):
    for cluster in range(0,k):
        clust = pd.DataFrame(kmeans.cluster_centers_[cluster])
        clust.index = movieMatrix.columns
        #print(clust)
        #sortDF = pd.DataFrame(clust,terms)
        #print(sortDF)
        sortDF = clust.sort_values(by=[0],ascending=False)
        #print(sortDF.loc[sortDF.index[0]][0])
        #print(sortDF)
        print("Top movies in Cluster", cluster+1)
        top_movies(sortDF, n)
        print("")

So these are the top movies found in each cluster:

In [18]:
print_clusters(kmeans,10,10)

Top movies in Cluster 1
The Shawshank Redemption: Special Edition 4.263620386643233
The Sixth Sense 4.224956063268893
The Silence of the Lambs 4.165787932044522
Forrest Gump 4.134739308728764
American Beauty 4.096074985354423
Good Will Hunting 3.975981253661395
Lord of the Rings: The Fellowship of the Ring 3.916813122437024
Finding Nemo (Widescreen) 3.9144698301113063
Pirates of the Caribbean: The Curse of the Black Pearl 3.9086115992970125
The Usual Suspects 3.908611599297012

Top movies in Cluster 2
Raiders of the Lost Ark 4.534983853606027
Forrest Gump 4.5306781485468255
The Matrix 4.526372443487621
Indiana Jones and the Last Crusade 4.519913885898816
The Sixth Sense 4.518837459634016
Braveheart 4.506996770721205
Shrek (Full-screen) 4.4973089343379975
Lord of the Rings: The Fellowship of the Ring 4.4833153928955864
Independence Day 4.474703982777179
Pirates of the Caribbean: The Curse of the Black Pearl 4.460710441334769

Top movies in Cluster 3
The Matrix 4.365351629502573
Gladiator 4.353916523727843
Forrest Gump 4.284734133790738
Braveheart 4.283018867924528
The Sixth Sense 4.261292166952544
The Green Mile 4.197827329902803
Raiders of the Lost Ark 4.197827329902801
Lord of the Rings: The Two Towers 4.194396798170383
Independence Day 4.174957118353344
Pirates of the Caribbean: The Curse of the Black Pearl 4.168096054888508

Top movies in Cluster 4
Pulp Fiction 4.527402135231316
The Godfather 4.355160142348755
The Usual Suspects 4.316725978647688
The Silence of the Lambs 4.267615658362989
Raiders of the Lost Ark 4.243416370106761
GoodFellas: Special Edition 4.241281138790036
Reservoir Dogs 4.232740213523133
Fight Club 4.227046263345198
American Beauty 4.205693950177936
Apocalypse Now 4.192882562277581

Top movies in Cluster 5
Raiders of the Lost Ark 4.447819314641745
Forrest Gump 4.379283489096574
Indiana Jones and the Last Crusade 4.2352024922118385
The Green Mile 4.2352024922118385
The Shawshank Redemption: Special Edition 4.228193146417445
Braveheart 4.214953271028037
The Sixth Sense 4.172118380062305
Gladiator 4.136292834890965
Saving Private Ryan 4.101246105919003
The Fugitive 4.0965732087227416

Top movies in Cluster 6
Finding Nemo (Widescreen) 4.404480398257623
Pretty Woman 4.364032358431859
Forrest Gump 4.345986309894213
The Sixth Sense 4.314872433105165
Shrek (Full-screen) 4.3136278780336035
Monsters 4.293092719352831
Pirates of the Caribbean: The Curse of the Black Pearl 4.269446172993156
Grease 4.255756067205973
Dirty Dancing 4.166770379589299
Shrek 2 4.158680771624146

Top movies in Cluster 7
Raiders of the Lost Ark 4.5678233438485805
The Godfather 4.4637223974763405
The Silence of the Lambs 4.406940063091483
The Shawshank Redemption: Special Edition 4.356466876971609
The Sixth Sense 4.356466876971609
Lord of the Rings: The Fellowship of the Ring 4.315457413249211
The Matrix 4.302839116719243
Indiana Jones and the Last Crusade 4.28391167192429
Lord of the Rings: The Two Towers 4.2586750788643535
GoodFellas: Special Edition 4.242902208201893

Top movies in Cluster 8
Raiders of the Lost Ark 4.600907029478457
Pulp Fiction 4.592403628117914
The Matrix 4.583900226757369
The Shawshank Redemption: Special Edition 4.4971655328798175
Lord of the Rings: The Fellowship of the Ring 4.481292517006802
Lord of the Rings: The Two Towers 4.450680272108844
Fight Club 4.4484126984126995
Braveheart 4.444444444444445
The Usual Suspects 4.433673469387758
Indiana Jones and the Last Crusade 4.415532879818595

Top movies in Cluster 9
Raiders of the Lost Ark 4.094430992736077
Lord of the Rings: The Fellowship of the Ring 4.066182405165456
Lord of the Rings: The Two Towers 4.019370460048426
The Matrix 3.9717514124293785
Pirates of the Caribbean: The Curse of the Black Pearl 3.883777239709443
Indiana Jones and the Last Crusade 3.8442292171105734
Lord of the Rings: The Return of the King 3.815173527037934
The Terminator 3.7037933817594832
The Sixth Sense 3.672316384180791
Independence Day 3.578692493946731

Top movies in Cluster 10
To Kill a Mockingbird 4.239473684210525
The Godfather 4.169298245614035
Rear Window 4.150877192982456
One Flew Over the Cuckoo's Nest 4.084210526315788
Citizen Kane 4.078070175438597
The Graduate 4.042982456140352
Amadeus 4.025438596491229
North by Northwest 3.9728070175438606
Chinatown 3.9377192982456135
Vertigo 3.9359649122806992

Function to print top n movies in a cluster ignoring movies the user has already seen and rated:

In [19]:
def top_movies_user(df, n):
    watched = []
    for movie in user_ratings:
        watched.append([movie][0][0])
    moviesreturned = 0
    movieidx = 0
    while moviesreturned != n:
        if df.index[movieidx] not in watched:
            print(toTitle(df.index[movieidx]),df.loc[df.index[movieidx]][0])
            movieidx += 1
            moviesreturned +=1
        else:
            movieidx +=1

Function to print a singular cluster:

In [20]:
def print_clust(kmeans, k, n):
        clust = pd.DataFrame(kmeans.cluster_centers_[k-1])
        clust.index = movieMatrix.columns
        #print(clust)
        #sortDF = pd.DataFrame(clust,terms)
        #print(sortDF)
        sortDF = clust.sort_values(by=[0],ascending=False)
        #print(sortDF.loc[sortDF.index[0]][0])
        #print(sortDF)
        print("Top movies in Cluster", k)
        top_movies_user(sortDF, n)
        print("")

Function to convert user input from the start of the application into a row of data, passable into kmeans

In [21]:
def user_row(user_data):
    out = pd.DataFrame(np.zeros(len(movieMatrix.columns)), index=movieMatrix.columns).T
    for rating in user_data:
        out[rating[0]] = rating[1]
    out = np.array(out)
    return out

In [22]:
user_data = user_row(user_ratings)

Cluster prediction for new user:

In [23]:
user_cluster = kmeans.predict(user_data)

Adding a 1 to the user cluster because we don't want a cluster 0

In [24]:
print("User belongs to cluster:", user_cluster[0]+1)

User belongs to cluster: 9

Recommended movies from that cluster excluding movies already seen by the user:

In [25]:
print_clust(kmeans, user_cluster[0]+1, 10)

Top movies in Cluster 9
Lord of the Rings: The Two Towers 4.019370460048426
The Matrix 3.9717514124293785
Indiana Jones and the Last Crusade 3.8442292171105734
Lord of the Rings: The Return of the King 3.815173527037934
The Terminator 3.7037933817594832
The Sixth Sense 3.672316384180791
Independence Day 3.578692493946731
Men in Black 3.5778853914447137
Star Wars: Episode V: The Empire Strikes Back 3.5690072639225185
Gladiator 3.5391444713478606

Lets try it again using average instead of 0's. 0's favor the most often rated movies too much

In [26]:
movieMatrix = movies.pivot_table(values='Rating', index='CustomerID', columns='MovieID')

Using the global average + the average of each movie divided by the number of ratings

In [27]:
globalavg = movieMatrix.mean().mean()
rating_sums= movieMatrix.sum(axis=0) 
rating_count = movieMatrix.count(axis=0)
missing_ratings = (rating_sums + globalavg*25) / (25+rating_count)

In [28]:
movieMatrix = movieMatrix.fillna(missing_ratings)
movieMatrix

MovieID,1,2,3,4,5,6,8,10,11,12,...,17761,17762,17763,17764,17765,17766,17767,17768,17769,17770
CustomerID,,,,,,,,,,,,,,,,,,,,,
769,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,2.000000,3.210411,3.000000,2.534275,3.063489,2.770233,2.827028,2.532746,2.823785
1333,3.441501,2.648875,4.000000,2.582291,3.214042,2.890785,3.000000,2.798204,2.783513,3.341931,...,4.000000,3.000000,1.000000,4.000000,2.534275,3.063489,4.000000,2.827028,2.532746,2.823785
1442,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,3.461434,3.210411,4.000000,2.534275,3.063489,2.770233,2.827028,2.532746,2.823785
2213,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,4.000000,3.210411,4.000000,2.534275,3.063489,2.770233,3.000000,2.532746,4.000000
2455,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,3.000000,3.210411,3.000000,2.534275,3.063489,2.770233,3.000000,2.532746,3.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2648589,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,4.000000,3.210411,5.000000,2.534275,3.063489,2.770233,2.827028,2.532746,2.823785
2648734,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,4.000000,3.210411,5.000000,2.534275,3.063489,2.770233,2.827028,2.532746,2.823785
2648869,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,4.000000,3.210411,5.000000,2.534275,3.063489,2.770233,2.827028,2.532746,2.823785
2648885,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,3.461434,3.210411,3.755668,2.534275,3.063489,2.770233,2.827028,2.532746,2.823785
2649285,3.441501,2.648875,3.333578,2.582291,3.214042,2.890785,2.986066,2.798204,2.783513,3.341931,...,2.833597,3.000000,3.210411,4.000000,2.534275,3.063489,2.770233,2.827028,2.532746,2.823785

In [29]:
movie_arr = np.array(movieMatrix)

In [30]:
kmeans = KMeans(n_clusters=10)
kmeans.fit(movie_arr)

KMeans(n_clusters=10)

In [31]:
user_cluster = kmeans.predict(user_data)

In [32]:
print("User belongs to cluster:", user_cluster[0]+1)

User belongs to cluster: 9

In [33]:
print_clust(kmeans, user_cluster[0]+1, 10)

Top movies in Cluster 9
Black Hawk Down 4.682085980811106
Schindler's List 4.344218452981165
Lord of the Rings: The Return of the King: Bonus Material 4.177191778428928
Lost: Season 1 4.146058021619056
Saving Private Ryan 4.142857142857143
Lord of the Rings: The Return of the King 4.142857142857143
The Hunt for Red October 4.1384084215944865
The Passion of the Christ 4.055012106393926
Million Dollar Baby 4.043872684389425
Lord of the Rings: The Two Towers: Bonus Material 4.037858275601058

### Now we will recommend movies using K Nearest Neighbor Classification:

### user based recommender 
#### find best key

In [34]:
from sklearn.neighbors import NearestNeighbors
from math import sqrt
from sklearn.metrics import mean_squared_error
import math

In [35]:

import os
cwd = os.getcwd()

In [36]:
df = pd.read_pickle('cleanedMovie.pkl')

In [37]:
user_movie_df = df.pivot(index='CustomerID',columns ='MovieID' ,values='Rating').fillna(0)
user_movie_df

MovieID,1,2,3,4,5,6,8,10,11,12,...,17761,17762,17763,17764,17765,17766,17767,17768,17769,17770
CustomerID,,,,,,,,,,,,,,,,,,,,,
769,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
1333,0.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,4.0,3.0,1.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0
1442,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2213,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,4.0
2455,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2648589,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
2648734,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
2648869,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
2648885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2649285,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
movie_names = list(user_movie_df.columns) 
customer_names = list(user_movie_df.index.values)

In [39]:
user_movie_df_rename = user_movie_df

In [40]:
user_movie_df_rename.columns = range(16795)

In [41]:
user_movie_df_rename = user_movie_df_rename.reset_index()

In [42]:
user_movie_df_rename = user_movie_df_rename.drop(columns=['CustomerID'])
user_movie_df_rename

,0,1,2,3,4,5,6,7,8,9,...,16785,16786,16787,16788,16789,16790,16791,16792,16793,16794
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,4.0,3.0,1.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,4.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13136,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
13137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
13138,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
13139,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:

users_movie_array = user_movie_df_rename.values
users_movie_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
from sklearn.neighbors import NearestNeighbors

In [45]:

def cross_validate_user(dataMat, movie, test_ratio, k):

    number_of_users = np.shape(dataMat)[0] 
    rated_items_by_user = np.array([i for i in range(number_of_users) if dataMat[i,movie]>0])
    test_size = math.ceil(test_ratio * len(rated_items_by_user))  # round up the test_size
    test_indices = np.random.randint(0, len(rated_items_by_user), test_size)
    withheld_users = rated_items_by_user[test_indices]
    original_movie_profile = np.copy(dataMat[:, movie])
    dataMat[withheld_users, movie] = 0 # So that the withheld test items is not used in the rating estimation below
    error_u = 0.0
    count_u = len(withheld_users)
    # Compute absolute error for user u over all test items
    knn = NearestNeighbors(metric='cosine',algorithm = 'brute', n_neighbors=k)
    knn.fit(dataMat)
    for user in withheld_users:
        sum_predict = 0
        count_predict = 0 

        # Estimate rating on the withheld item
        neigh_dist, neigh_ind= knn.kneighbors(dataMat[user, :].reshape(1, 16795), n_neighbors=k+1)
        distLst = neigh_dist.tolist()[0][1:]
        indLst = neigh_ind.tolist()[0][1:]

        for j in indLst:
            if original_movie_profile[j] != 0:
                sum_predict += original_movie_profile[j]
                count_predict += 1
        if count_predict == 0:
            continue
        else:
            estimatedScore = sum_predict/count_predict
            error_u = error_u + abs(estimatedScore - original_movie_profile[user])

    # Now restore ratings of the withheld items to the user profile
    for user in withheld_users:
        dataMat[user, movie] = original_movie_profile[user]

    # Return sum of absolute errors and the count of test cases for this user
    # Note that these will have to be accumulated for each user to compute MAE
    return error_u, count_u

In [46]:
def test(dataMat, test_ratio, k):
# Write this function to iterate over all users and for each perform evaluation by calling
# the above cross_validate_user function on each user. MAE will be the ratio of total error 
# across all test cases to the total number of test cases, for all users
    total_error = 0
    cases_number = 0
    movies_number = np.shape(dataMat)[1]
    test_size = math.ceil(test_ratio * movies_number)
    test_indices = np.random.randint(0, movies_number, test_size)
    for movie in test_indices:
        error_user, count_user = cross_validate_user(dataMat, movie, test_ratio, k)
        total_error += error_user
        cases_number += count_user
    MAE = total_error/cases_number
    return MAE

Uncomment to run to determine the best K: takes close to an hour to complete
View results on seperate notebook:  KNN_3.ipynb

In [47]:
#from tqdm import tqdm

#KLst = [10, 30, 50]
#for k in tqdm(KLst):
    #MAE = test(users_movie_array, 0.005, k)
    #print(MAE)
    #print('-'*40)

make recommendation

In [48]:
user_movie_df = df.pivot(index='CustomerID',columns ='MovieID' ,values='Rating').fillna(0)
user_movie_df

MovieID,1,2,3,4,5,6,8,10,11,12,...,17761,17762,17763,17764,17765,17766,17767,17768,17769,17770
CustomerID,,,,,,,,,,,,,,,,,,,,,
769,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
1333,0.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,4.0,3.0,1.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0
1442,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2213,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,4.0
2455,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2648589,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
2648734,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
2648869,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
2648885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2649285,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
from sklearn.neighbors import NearestNeighbors
knn = NearestNeighbors(metric='cosine',algorithm = 'brute', n_neighbors=10)

In [50]:
movie_title = pd.read_csv("movie_titles.csv", encoding='unicode_escape', usecols=[2], header=None)
movie_title.columns = ['title']
movie_title

                                                   title
0                                        Dinosaur Planet
1                             Isle of Man TT 2004 Review
2                                              Character
3                           Paula Abdul's Get Up & Dance
4                               The Rise and Fall of ECW
...                                                  ...
17765  Where the Wild Things Are and Other Maurice Se...
17766                  Fidel Castro: American Experience
17767                                              Epoch
17768                                        The Company
17769                                       Alien Hunter

[17770 rows x 1 columns]

In [51]:
# create a function which takes a movie name and make recommedation for it
recommendation = {}
def make_recommendation(input_user,data,model,n_recommendation):
    model.fit(data)
    input_user_array = input_user.to_numpy()
    similar_users_list = (model.kneighbors(input_user_array,n_neighbors=n_recommendation+1,return_distance=False)).tolist()
    for i in similar_users_list[0][1:]:
        for j in data.columns:
            ratingLst = []
            if int(input_user[j]) == 0 and data.iloc[i][j] > 3:
                if j not in recommendation:
                    ratingLst.append(data.iloc[i][j])
                    recommendation[j] = ratingLst
                else:
                    recommendation.get(j).append(data.iloc[i][j])
    print("The new user who will like following movies.")
    number = 0
    for k in sorted(recommendation, key=lambda k: len(recommendation[k]), reverse=True):
        if number < 5:
            res = movie_title.loc[k-1]['title']
            print(res)
            number += 1 #recommend top 5 movies

In [52]:
#convert user_ratings from list to dataframe
# create a empty dataframe
column_names = movie_names
df_newUser = pd.DataFrame(columns = column_names)

In [53]:
for i in user_ratings:
    df_newUser.at[0 , i[0]] = i[1]
df_newUser

,1,2,3,4,5,6,8,10,11,12,...,17761,17762,17763,17764,17765,17766,17767,17768,17769,17770
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
#check input:
df_newUser.isna().sum().sum()

16785

In [55]:
newUser_df = df_newUser.fillna(0)
newUser_df

,1,2,3,4,5,6,8,10,11,12,...,17761,17762,17763,17764,17765,17766,17767,17768,17769,17770
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [56]:
make_recommendation(newUser_df, user_movie_df, knn, 10)

The new user who will like following movies.
The Usual Suspects
Good Will Hunting
Lord of the Rings: The Two Towers
Saving Private Ryan
Braveheart

#### item based recommender
#### find best key

In [57]:
# pivot data to movie-users matrix
movie_users_df = df.pivot(index='MovieID',columns = 'CustomerID',values='Rating').fillna(0)
movie_users_df_rename = movie_users_df
movie_users_df_rename.columns = range(13141)
movie_users_df_rename = movie_users_df_rename.reset_index()
movie_users_df_rename = movie_users_df_rename.drop(columns=['MovieID'])

In [58]:
movie_users_array = movie_users_df_rename.values

In [59]:
from sklearn.neighbors import NearestNeighbors

In [60]:
def cross_validate_user(dataMat, user, test_ratio, k):

    number_of_items = np.shape(dataMat)[0] 
    rated_items_by_user = np.array([i for i in range(number_of_items) if dataMat[i,user]>0])
    test_size = math.ceil(test_ratio * len(rated_items_by_user))  # round up the test_size
    test_indices = np.random.randint(0, len(rated_items_by_user), test_size)
    withheld_items = rated_items_by_user[test_indices]
    original_user_profile = np.copy(dataMat[:,user])
    dataMat[withheld_items, user] = 0 # So that the withheld test items is not used in the rating estimation below
    error_u = 0.0
    count_u = len(withheld_items)
    # Compute absolute error for user u over all test items
    knn = NearestNeighbors(metric='cosine',algorithm = 'brute', n_neighbors=k)
    knn.fit(dataMat)
    for item in withheld_items:
        sum_predict = 0
        count_predict = 0
        # Estimate rating on the withheld item
        neigh_dist, neigh_ind= knn.kneighbors(dataMat[item, :].reshape(1, 13141), n_neighbors=k+1)
        distLst = neigh_dist.tolist()[0][1:]
        indLst = neigh_ind.tolist()[0][1:]
        for j in indLst:
            if original_user_profile[j] != 0:
                sum_predict += original_user_profile[j]
                count_predict += 1
        if count_predict == 0:
            continue
        else:
            estimatedScore = sum_predict/count_predict   
            error_u = error_u + abs(estimatedScore - original_user_profile[item])

    # Now restore ratings of the withheld items to the user profile
    for item in withheld_items:
        dataMat[item, user] = original_user_profile[item]

    # Return sum of absolute errors and the count of test cases for this user
    # Note that these will have to be accumulated for each user to compute MAE
    return error_u, count_u

In [61]:
def test(dataMat, test_ratio, k):
# Write this function to iterate over all users and for each perform evaluation by calling
# the above cross_validate_user function on each user. MAE will be the ratio of total error 
# across all test cases to the total number of test cases, for all users
    total_error = 0
    cases_number = 0
    users_number = np.shape(dataMat)[1]
    test_size = math.ceil(test_ratio * users_number)
    test_indices = np.random.randint(0, users_number, test_size)
    for user in test_indices:
        error_user, count_user = cross_validate_user(dataMat, user, test_ratio, k)
        total_error += error_user
        cases_number += count_user
    MAE = total_error/cases_number
    return MAE

In [62]:
#KLst = [10, 30, 50]
#for k in KLst:
    #MAE = test(movie_users_array, 0.005, k)
    #print(MAE)
    #print('-'*40)

k = 30 turns out to be the best result

make recommendation:

In [63]:
movie_users_df = df.pivot(index='MovieID',columns = 'CustomerID',values='Rating').fillna(0)

In [64]:
newUser_dict = {}
for i in user_ratings:
    newUser_dict[i[0]] = i[1]
newUser_dict

{11283: 4,
 1905: 4,
 14410: 5,
 2862: 5,
 14312: 4,
 6971: 4,
 15107: 4,
 10042: 5,
 2452: 4,
 11064: 4}

In [65]:
#find top 3 favorite movies of the new user
newUser_dict_sort = dict(sorted(newUser_dict.items(), key=lambda item: item[1],reverse=True))
top3movies = {k: newUser_dict_sort[k] for k in list(newUser_dict_sort)[:3]}
top3movies

{14410: 5, 2862: 5, 10042: 5}

In [66]:
from sklearn.neighbors import NearestNeighbors
knn = NearestNeighbors(metric='cosine',algorithm = 'brute', n_neighbors=30)

In [67]:

def find_similarity(topMovies,data,model,n_recommendation):
    dict_similarity = {}
    model.fit(data)
    for index in topMovies:
        array_index = data.iloc[index].to_numpy()
        neigh_dist, neigh_ind = model.kneighbors(array_index.reshape(1, 13141),n_neighbors=n_recommendation+1)
        neigh_dist_Lst = neigh_dist.tolist()[0][1:] #ignore itself
        neigh_ind_Lst = neigh_ind.tolist()[0][1:]
        for i in range(len(neigh_dist_Lst)):
            if neigh_ind_Lst[i] not in dict_similarity:
                dict_similarity[neigh_ind_Lst[i]] = (1-neigh_dist_Lst[i]) * topMovies.get(index)
            else:
                ratio = dict_similarity.get(neigh_ind_Lst[i])
                new_ratio = (ratio + (1-neigh_dist_Lst[i]) * topMovies.get(index))/2
                dict_similarity[neigh_ind_Lst[i]] = new_ratio
            
    sort_dict = dict(sorted(dict_similarity.items(), key=lambda item: item[1],reverse=True))
    return sort_dict

In [68]:
def make_recommendation(topMovies, newUser_rating, data, model, n_recommendation):    
    count = 0
    sort_dict = find_similarity(topMovies,data,model,n_recommendation)
    print("The new user who will like following movies:")
    for movie_ind in sort_dict:
        if count < 5:
            if int(newUser_rating[movie_ind]) == 0:
                res = movie_title.loc[movie_ind-1]['title']
            print(res)
            count += 1
    return

In [69]:
make_recommendation(top3movies, newUser_df, movie_users_df,knn,10)

The new user who will like following movies:
Still
The Inspector Lynley Mysteries: A Traitor to Memory
Outrage
Layer Cake
The Fassbinder Collection: Pioneer in Ingolstadt

# SVD Predictor

Creating and testing the SVD Predictor model on our dataframe. First we need to split the data in train and test set, and then run GridSearchCV on the training set in order to find the best n factors value to pass into the SVD model creation.

In [ ]:
import pickle
from datetime import datetime
from tqdm import tqdm
import numpy as np
import pandas as pd
import os
import sklearn
from sklearn.metrics.pairwise import cosine_similarity
import random
from surprise import Reader, Dataset
from surprise import SVD
from surprise import SVDpp
from surprise.model_selection import GridSearchCV
import xgboost as xbg
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
movie = pd.read_pickle("cleanedMovie.pkl")
movie.head()

In [ ]:
movie_train, movie_test = sklearn.model_selection.train_test_split(movie, train_size = 0.8)

In [ ]:
print(movie_test.shape)
movie_test.head()

In [ ]:
print(movie_train.shape)
movie_train.head()

In [ ]:
reader = Reader(rating_scale=(1,5))
movieInput = pd.DataFrame()
movieInput['CustomerID'] = movie_train['CustomerID']
movieInput['MovieID'] = movie_train['MovieID']
movieInput['Rating'] = movie_train['Rating']

train_data = Dataset.load_from_df(movieInput, reader)
trainset = train_data.build_full_trainset()

In [ ]:
testset = list(zip(movie_test["CustomerID"].values, movie_test["MovieID"].values, movie_test["Rating"].values))

In [ ]:
error_table = pd.DataFrame(columns = ["Model", "Train_RMSE", "Test_RMSE"])

In [ ]:
trainset.global_mean

## Creating Fit and Prediction Method

In [ ]:
def run_surprise(algo, trainset, testset, model_name):
    start = datetime.now()
    algo.fit(trainset)
    
    pred_train = algo.test(trainset.build_testset())
    
    trainActual = np.array([p.r_ui for p in pred_train])
    trainPred = np.array([p.est for p in pred_train]) 
    trainRMSE = np.sqrt(mean_squared_error(trainActual, trainPred))
    
    print("Train Data RMSE: {}".format(trainRMSE))
    print("\n")
    
    train = {"RMSE": trainRMSE, "Prediction": trainPred}
    
    pred_test = algo.test(testset)
    testActual = np.array([p.r_ui for p in pred_test])
    testPred = np.array([p.est for p in pred_test])
    testRMSE = np.sqrt(mean_squared_error(testActual, testPred))
    
    print("Test Data RMSE: {}".format(testRMSE))
    print("\n")
    
    test = {"RMSE": testRMSE, "Prediction": testPred}
    
    print("Time Taken = " + str(datetime.now() - start))
        
    return train, test

## Finding N Factors

GridSearchCV cannot handle the amount of data we are passing through, so we will run GridSearchCV on a smaller portion of the dataset in order to return the best n_factors to pass into SVD. SVD will itself get the full dataset we are using. Only run the code below for GridSearchCV if you want to run through the whole code. The fit command can take up to an hour, and the results are always the same, so we can hard code in the parameter for SVD.

In [ ]:
params = { 'n_factors': [5, 10, 15, 20, 25, 30, 35, 40, 50]}
grid = GridSearchCV(SVD, params, measures=['rmse'], cv=3, refit=True)
grid.fit(Dataset.load_from_df(movieInput.iloc[:1500000], reader))
print(grid.best_score['rmse'])

Of the N factors passed in, we can find the one that had the best RMSE and use that in the SVD model. Below, we use that directly from the calculation above. In the following class file, we use the value as a static variable in order to minimize processing time on unnecessary calculations. The results of grid.best_params['rmse']['n_factors'] are always 5, so feel free to input that into the parameters.

In [ ]:
algo = SVD(n_factors = grid.best_params['rmse']['n_factors'], biased=True, verbose=True)
train_result, test_result = run_surprise(algo, trainset, testset, "SVD")

The best results for the test data are RMSE of 0.829, which is an extremely good RMSE for the Netflix Prize Data! Of course, the data may be somewhat skewed from only taking the most active users and popular movies. However, for our data of active users, this is highly effective! We can test below on less active users to see the RMSE for users we didn't include.

## Testing on Unused Data

Here we read in some of the rest of the data that was not passed into the pickle file in the beginning. We test for the RMSE of this test data using the SVD algorithm above.

In [ ]:
cwd = os.getcwd()
movie = pd.read_csv(cwd + "/data/final.csv")
movie.describe()

In [ ]:
reduced_data = movie.drop(columns=['Date'])

reduced_data['MovieID'] = reduced_data['MovieID'].astype('int16')
reduced_data['CustomerID'] = reduced_data['CustomerID'].astype('int32')
reduced_data['Rating'] = reduced_data['Rating'].astype('int8')

In [ ]:
movie_freq = pd.DataFrame(reduced_data.groupby('MovieID').size(),columns=['count'])
threshold = 100

popular_movies = list(set(movie_freq.query('count>=@threshold').index))

# ratings df after dropping non popular movies
data_popular_movies = reduced_data[reduced_data.MovieID.isin(popular_movies)]

print('shape of original data:', reduced_data.shape)
print('shape of data_popular_movies', data_popular_movies.shape)
print("No. of movies which are rated more than 100 times:", len(popular_movies))

In [ ]:
# reduce data_popular_movie to only have movies that are in movie
movieList = movie.MovieID.tolist()
popMoviesTest = data_popular_movies[data_popular_movies.MovieID.isin(movieList)]

The below code takes a very long time to run as well, as it is 100,000,000 rows of data being passed in. You can uncomment the line near the top to reduce the dataset to a more manageable size. If not, it takes about an hour to run.

In [ ]:
start = datetime.now()

reducedtestset = list(zip(popMoviesTest["CustomerID"].values, popMoviesTest["MovieID"].values, popMoviesTest["Rating"].values))
#reducedtestset = reducedtestset.iloc[:2000000]

pred_test = algo.test(reducedtestset)
testActual = np.array([p.r_ui for p in pred_test])
testPred = np.array([p.est for p in pred_test])
testRMSE = np.sqrt(mean_squared_error(testActual, testPred))
    
print("Test Data RMSE: {}".format(testRMSE))
print("\n")
    
test = {"RMSE": testRMSE, "Prediction": testPred}
    
print("Time Taken = " + str(datetime.now() - start))

Based on the RMSE from the test set we just ran, our algorithm is definitely biased toward users who have rated very frequently. There is likely a high level of correlation between those users, which affects our results. This proves that our algorithm is highly effective for those users, but only average for users who do not rate in the top percentile.

However, the testing we ran on the full data set of users may not have provided accurate results as the model can not accurately predict ratings for users that were not at all in the training data. For those users, they would receive a rating that does not take into account their personal preference or bias.

## Creating a Mini-Recommender

Though we already have 2 models for recommenders, we can also use the SVD model as a recommender for a Customer at a time. Below is code to recommend 10 movies to a given Customer.

In [ ]:
def recommendFor(customerID, model):
    predictions = []
    ids = []
    for mov in movie.MovieID.unique().tolist():
        predictions.append(model.predict(customerID, mov).est)
        ids.append(mov)
    return predictions, ids

In [ ]:
preds, movIds = recommendFor(1, svd)

In [ ]:
def recommendedMovies(count, preds, movs):
    movieAndRating = {}
    copyPreds = preds[:]
    for i in range(count):
        index = copyPreds.index(max(copyPreds))
        maxPred = max(copyPreds)
        mov = movs[index]
        title = movie_title.iloc[mov-1:mov]['title'][mov-1]
        movieAndRating[title] = maxPred
        copyPreds.pop(index)
    return movieAndRating

In [ ]:
recommendedMovies(10, preds, movIds)

The final product is a recommender that returns the count of top movies for the chosen Customer, and gives the predicted rating. The recommender is also a part of the class above, so let's test it out.

## Putting it all together

Take all the information we gathered, the functions we built, and the models we created, and put them all into one class. The class saves algorithms as pickle files to be reused later without having to calculate the model and algorithm all over again. The class also has no testset, as there is no need for verification at this stage- only fitting the model and predicting values for the given user.

In [ ]:
import pickle
from tqdm import tqdm
import numpy as np
import pandas as pd
import os
import pathlib
from surprise import Reader, Dataset
from surprise import SVD
from surprise import SVDpp
from surprise.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

class SVDPredictor:
    error_table = pd.DataFrame(columns = ["Model", "Train_RMSE", "Test_RMSE"])
    
    #Class takes in final.csv as a whole as a DataFrame
    def __init__(self, data, titles):
        self.movie = data
        self.titles = titles
        self._createAlgorithmFromData()
        
    def _createAlgorithmFromData(self):
        #check if algo and trainset/train_data files are already created
        file = pathlib.Path('svd.pickle')
        if not file.exists():
            self._reduceDataSize()
            self._splitMovie()
            self._createTrainSet()
        self._run_surprise()
        
    def recommendFor(self, customerID, count):
        preds = []
        ids = []
        for mov in self.movie.MovieID.unique().tolist():
            preds.append(self.predict(customerID, mov).est)
            ids.append(mov)
            
        movieAndRating = {}
        copyPreds = preds[:]
        for i in range(count):
            index = copyPreds.index(max(copyPreds))
            maxPred = max(copyPreds)
            mov = ids[index]
            title = movie_title.iloc[mov-1:mov]['title'][mov-1]
            movieAndRating[title] = maxPred
            copyPreds.pop(index)
        return movieAndRating
        
    def predict(self, userID, movieID):
        #use algo to predict rating. Return predicted rating
        return self.algo.predict(userID, movieID)
    
    def _splitMovie(self):
        self.movie = self.movie.iloc[:1500000]
        
    def _createTrainSet(self):
        reader = Reader(rating_scale=(1,5))
        movieInput = pd.DataFrame()
        movieInput['CustomerID'] = self.movie['CustomerID']
        movieInput['MovieID'] = self.movie['MovieID']
        movieInput['Rating'] = self.movie['Rating']

        self.train_data = Dataset.load_from_df(movieInput, reader)
        self.trainset = self.train_data.build_full_trainset()
        #write to a file
    
    def _reduceDataSize(self):
        self.movie['Date'] = self.movie['Date'].astype('category')
        self.movie['MovieID'] = self.movie['MovieID'].astype('int16')
        self.movie['CustomerID'] = self.movie['CustomerID'].astype('int32')
        self.movie['Rating'] = self.movie['Rating'].astype('int8')
    
    def _run_surprise(self):
        file = pathlib.Path('svd.pickle')
        if file.exists():
            with open('svd.pickle', 'rb') as f:
                self.algo = pickle.load(f)
        else:
            self.algo = SVD(n_factors = 5, biased=True, verbose=True)
            self.algo = self.algo.fit(self.trainset)
            with open('svd.pickle', 'wb') as f:
                pickle.dump(self.algo, f)

Let's now instantiate the class we just created above with our curated data set, and then test it on a random CustomerID and MovieID! In the actual application of a recommender, we would want to set a specific CustomerID, but allow the MovieID to vary to get our ratings.

In [ ]:
svd = SVDPredictor(movie, movie_title)

In [ ]:
print("Prediction for Customer 1 and Movie 5: ", svd.predict(1, 12).est)
print("Prediction for Customer 1 and Movie 16378: ", svd.predict(7, 16368).est)

In [ ]:
svd.recommendFor(2, 10)